import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import logoSrc from '../../images/kingfisher-logo.png'

const DEFAULT_FOOTER = `REPORT DISCLAIMER: This report has been generated by the Kingfisher Hotel Management System for internal management and operational purposes. Every effort has been made to ensure accuracy and completeness; any updates will be reflected in future reports. This report is intended solely for authorized personnel and should not be distributed without proper authorization.

END OF REPORT

Generated by Kingfisher Hotel Management System | Kingfisher Beach Resort © 2026. All Rights Reserved.`

function toCSV(rows, headers) {
  const escape = (v) => `"${String(v ?? '').replace(/"/g, '""')}"`
  const lines = [headers.map(escape).join(',')]
  rows.forEach((r) => lines.push(headers.map((h) => escape(r[h])).join(',')))
  return lines.join('\n')
}

function downloadFile(content, filename, mime) {
  const blob = new Blob([content], { type: mime })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

function formatValue(value) {
  if (value === null || value === undefined || value === '') return '—'
  if (typeof value === 'number') return value.toLocaleString()
  return String(value)
}

function drawSummaryCards(doc, summary, startY, pageWidth) {
  if (!summary || summary.length === 0) return startY

  const cardWidth = (pageWidth - 40) / Math.min(summary.length, 3)
  summary.slice(0, 3).forEach((item, index) => {
    const x = 14 + index * (cardWidth + 6)
    doc.setFillColor(245, 247, 250)
    doc.roundedRect(x, startY, cardWidth, 20, 2, 2, 'F')
    doc.setDrawColor(205, 220, 240)
    doc.roundedRect(x, startY, cardWidth, 20, 2, 2, 'S')
    doc.setFontSize(7)
    doc.setTextColor(100, 110, 125)
    doc.text(String(item.label || 'Metric'), x + 4, startY + 8)
    doc.setFont(undefined, 'bold')
    doc.setFontSize(9)
    doc.setTextColor(15, 43, 70)
    doc.text(String(item.value ?? '—'), x + 4, startY + 15)
    doc.setFont(undefined, 'normal')
  })

  return startY + 28
}

function drawPieChart(doc, chart, startY, pageWidth) {
  try {
    const data = chart.data || []
    if (!data.length) return startY

    const total = data.reduce((sum, item) => sum + (Number(item.value) || 0), 0) || 1
    const colors = [
      [37, 99, 235],
      [16, 185, 129],
      [244, 114, 182],
      [245, 158, 11],
      [107, 114, 128],
    ]

    doc.setFontSize(9)
    doc.setTextColor(15, 43, 70)
    doc.text(String(chart.title || 'Distribution'), 14, startY)

    const barY = startY + 12
    const barWidth = Math.max(40, Math.min(pageWidth - 40, 120))
    let cursorX = 14

    data.forEach((item, index) => {
      const value = Number(item.value) || 0
      if (value <= 0) return
      const segmentWidth = (value / total) * barWidth
      doc.setFillColor(...colors[index % colors.length])
      doc.rect(cursorX, barY, segmentWidth, 8, 'F')
      cursorX += segmentWidth
    })

    doc.setDrawColor(220, 226, 235)
    doc.rect(14, barY, barWidth, 8, 'S')

    data.forEach((item, index) => {
      const color = colors[index % colors.length]
      doc.setFillColor(...color)
      doc.rect(14, barY + 18 + index * 8, 4, 4, 'F')
      doc.setTextColor(70, 70, 70)
      doc.setFontSize(7)
      doc.text(`${item.label || 'Item'} (${item.value ?? 0})`, 22, barY + 21 + index * 8)
    })

    return startY + 30 + Math.max(0, data.length - 1) * 8
  } catch (error) {
    doc.setFontSize(8)
    doc.setTextColor(100, 100, 100)
    doc.text(`${chart.title || 'Distribution'} unavailable in this browser environment`, 14, startY + 4)
    return startY + 14
  }
}

function drawSimpleChart(doc, chart, startY, pageWidth) {
  const data = chart.data || []
  if (!data.length) return startY

  const chartHeight = 48
  const chartWidth = pageWidth - 28
  const maxValue = Math.max(...data.map((item) => Number(item.value) || 0), 1)
  const gap = 10
  const barWidth = Math.max(10, (chartWidth - gap * (data.length + 1)) / data.length)

  doc.setFontSize(9)
  doc.setTextColor(15, 43, 70)
  doc.text(String(chart.title || 'Chart'), 14, startY)

  const plotY = startY + 8
  const plotHeight = chartHeight - 10
  doc.setDrawColor(220, 226, 235)
  doc.line(14, plotY + plotHeight, pageWidth - 14, plotY + plotHeight)

  data.forEach((item, index) => {
    const barHeight = Math.max(6, ((Number(item.value) || 0) / maxValue) * (plotHeight - 6))
    const x = 14 + gap * (index + 1) + index * barWidth
    const y = plotY + plotHeight - barHeight
    doc.setFillColor(37, 99, 235)
    doc.rect(x, y, barWidth, barHeight, 'F')
    doc.setTextColor(70, 70, 70)
    doc.setFontSize(6)
    doc.text(String(item.label || 'Item'), x, plotY + plotHeight + 8)
    doc.text(String(item.value ?? 0), x, y - 2)
  })

  return startY + chartHeight + 6
}

function drawCharts(doc, charts, startY, pageWidth) {
  let currentY = startY
  charts.forEach((chart, index) => {
    if (chart.type === 'pie') {
      currentY = drawPieChart(doc, chart, currentY, pageWidth)
    } else {
      currentY = drawSimpleChart(doc, chart, currentY, pageWidth)
    }
    // Add extra spacing between charts
    if (index < charts.length - 1) {
      currentY += 8
    }
  })
  return currentY
}

export function exportCSV(rows, filename = 'report.csv') {
  if (!rows || rows.length === 0) return
  const headers = Object.keys(rows[0] || {})
  const csv = toCSV(rows, headers)
  downloadFile(csv, filename, 'text/csv')
}

export function exportPDF(title, rows, filename = 'report.pdf', options = {}) {
  if (!rows || rows.length === 0) return
  const doc = new jsPDF()
  const pageWidth = doc.internal.pageSize.getWidth()

  doc.setFillColor(15, 43, 70)
  doc.rect(0, 0, pageWidth, 24, 'F')
  
  // Add logo to top left corner (wider size)
  doc.addImage(logoSrc, 'PNG', 2, 1, 28, 15)
  
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(14)
  doc.setFont(undefined, 'bold')
  const centerX = pageWidth / 2
  doc.text('Kingfisher Beach Resort', centerX, 9, { align: 'center' })
  doc.setFontSize(10)
  doc.text(`${title} — generated ${new Date().toLocaleDateString()}`, centerX, 18, { align: 'center' })

  let currentY = 34
  doc.setTextColor(15, 43, 70)
  doc.setFontSize(11)
  doc.setFont(undefined, 'bold')
  doc.text('Executive summary', 14, currentY)
  currentY = drawSummaryCards(doc, options.summary || [], currentY + 8, pageWidth)

  if (options.charts && options.charts.length > 0) {
    currentY = drawCharts(doc, options.charts, currentY + 4, pageWidth)
  }

  const tableStartY = Math.max(currentY + 12, 64)
  doc.setFontSize(10)
  doc.setFont(undefined, 'bold')
  doc.text('Detailed data', 14, tableStartY)

  autoTable(doc, {
    startY: tableStartY + 4,
    head: [Object.keys(rows[0] || {})],
    body: rows.map((r) => Object.values(r).map(formatValue)),
    styles: { fontSize: 8 },
    headStyles: { fillColor: [15, 43, 70] },
  })

  const footerText = options.footerText || DEFAULT_FOOTER
  doc.setFontSize(7)
  doc.setTextColor(100, 100, 100)
  
  // Add page break before footer if table extends too far
  const lastTableY = doc.lastAutoTable.finalY || tableStartY
  const footerStartY = Math.max(lastTableY + 20, doc.internal.pageSize.getHeight() - 70)
  
  // Format footer with full width, limited to 3-4 lines
  const footerLines = doc.splitTextToSize(footerText, pageWidth - 12)
  let yPosition = footerStartY
  
  footerLines.forEach((line) => {
    const lineWidth = doc.getTextWidth(line)
    const xPosition = (pageWidth - lineWidth) / 2
    doc.text(line, xPosition, yPosition)
    yPosition += 5
  })
  doc.save(filename)
}
